name: Deploy to Hugging Face

on:
  push:
    branches: ["main"]   # otomatis jalan setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # clone Space ke folder deploy_space (bukan hf-space, supaya tidak bentrok)
          git clone https://huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek deploy_space
          
          # hapus semua isi lama di Space
          rm -rf deploy_space/*
          
          # copy semua isi repo GitHub ke folder deploy_space
          cp -r ./* deploy_space/
          
          cd deploy_space
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
          git push https://USER:$HF_TOKEN@huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek main