name: Deploy to Hugging Face

on:
  push:
    branches: ["main"]   # otomatis jalan setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # clone Space kamu dari Hugging Face
          git clone https://huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek hf-space
          
          # hapus semua isi lama
          rm -rf hf-space/*
          
          # copy semua isi repo GitHub ke dalam space
          cp -r * hf-space/
          
          cd hf-space
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push https://USER:$HF_TOKEN@huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek main
