name: Deploy to Hugging Face

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # clone Space dengan full history (tanpa shallow clone)
          git clone https://huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek /tmp/deploy_space --depth=1
          cd /tmp/deploy_space
          git fetch --unshallow || true
          cd -

          # hapus semua isi lama
          rm -rf /tmp/deploy_space/*
          
          # copy isi repo ke Space
          rsync -av --exclude=".git" --exclude=".github" ./ /tmp/deploy_space/

          cd /tmp/deploy_space
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
          git push --force https://USER:$HF_TOKEN@huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek main