name: Deploy to Hugging Face

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # clone Space ke folder sementara
          git clone https://huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek /tmp/deploy_space
          
          # hapus semua isi lama
          rm -rf /tmp/deploy_space/*
          
          # copy isi repo ke Space
          cp -r . /tmp/deploy_space/
          
          cd /tmp/deploy_space
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
          
          # pakai --force agar menimpa remote branch
          git push --force https://USER:$HF_TOKEN@huggingface.co/spaces/franzxml/pemrograman_berorientasi_objek main